version: 0.0
os: linux 

files:
  - source: /
    destination: /home/app
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
      - location: ./scripts/after-install.sh
        timeout: 1000
        runas: root
  ApplicationStart:
    - location: ./scripts/application-start.sh     
      timeout: 300
      runas: root